import Layout from '../components/Layout/Layout';
import Head from 'next/head';
import styles from './css/top.module.css';

const Index = () => {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.top}>
        <img src="/top/vercel.svg" className={styles.vercel} alt="vercel logo" />
        {/* 画像はpublicフォルダのみ　ルール: スラッシュから始める */}
      </main>
    </Layout>
  );
}

export default Index;